### ISSUE TITLE
[1.1] Vendor response

### ISSUE THREAD

**Issue by Erquint** [RobertTheSable/fe3-translation#2]
Based on your README stating:
> This is a beta release, so please report any issues you find. Reporting issues with the 1.1 patch would be
    especially appreciated. 

ROM v1.1 here.
![Fire Emblem - Monshou no Nazo (J) (V1 1)  T+Eng _001](https://user-images.githubusercontent.com/4364856/163481392-a9c71103-2460-4983-9ba5-f71d167b4976.png)
Got a couple symbols of stray garbage in the vendor response upon purchase.

If this concerns you, let me know what additional debug info I can provide.

Strangely, only noticed this halfway through the first book. Unsure if it was present before.
In fact, I have played most of the first half of the first book on the 1.0 version of the ROM by mistake and later migrated the save (not a savestate) to 1.1, so that may be why. Could double-check by migrating back if you're planning to engage with investigating this.

**Comment by RobertTheSable** [comment]
I've seen this before. Looks like untranslated text.

https://github.com/RobertTheSable/fe3-translation/blob/master/project/text/shopping/35.txt

Edit: or it might be this: https://github.com/RobertTheSable/fe3-translation/blob/master/project/text/shopping/58.txt

Unfortunately I can't actually read Japanese so I don't know what to replace it with.

It may be intended to be filler, I see this [_81]s pattern in a few other places.

**Comment by RobertTheSable** [comment]
I checked in the same shop with my 1.1 ROM and I haven't seen the text. So it's some kind of weird conditional text.

**Comment by RobertTheSable** [comment]
I have identified the missing text.

![Screenshot_20220414_205117](https://user-images.githubusercontent.com/11481364/163506178-bd1e4e04-a040-420e-b1d9-91a5447c389e.png)

Apparently this text only happens when you buy an item in "supply mode" as Marth.

**Comment by RobertTheSable** [comment]
On further inspection, the text wasn't untranslated.

It looks like the "storage" table originally just had a list of item names, but either Quirino or VASM/RPGGuy (probably latter) added the "was sent to the storage text" to every single entry so that it fit the text box properly.

But they borked copying the substitution of the text, and so what should hove been a `00 81` in the rom became just `81`. hence the weird garbage Japanese text.

Luckily, the vendor text works, so I can just repoint both this text and the text for the secret shop and it should be fine.

Edit: Actually there's enough space in the text to just fix the command.

**Comment by RobertTheSable** [comment]
Fixed in 0.22.
